# Generated by Django 6.0.4 on 2026-06-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tasks', '0002_task_category_task_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('estimated_hours', models.IntegerField(blank=True, null=True, verbose_name='Предполагаемые часы')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tasks.task', verbose_name='Задача')),
            ],
        ),
    ]
